// src/lib/nfl/game-plays.ts
//
// Play-by-play fetch + classification for a single game. Powers QB Room
// (targets, depth/direction chart, red zone usage, formation split) and
// will feed Offensive/Defensive Coordinator tabs for whatever's honestly
// derivable from this data (rush/pass yardage splits, direction — NOT
// coverage/defensive-shape %, which is confirmed absent from ESPN's
// public API and will not be fabricated).
//
// Curl-verified 2026-08-16 against a real completed preseason game
// (TB @ NYJ, event 401873276):
//   https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/{id}/competitions/{id}/plays?limit=300
//
// CONFIRMED REAL FIELDS:
//   - text: auto-generated by ESPN, contains "(Shotgun)" prefix when
//     shotgun is used (absence = under center — binary, not a guess),
//     and "short"/"deep" + "left"/"middle"/"right" for pass plays.
//   - start.yardsToEndzone / end.yardsToEndzone: exact field position,
//     used for Red Zone detection (<=20).
//   - statYardage: actual yards gained on the play.
//   - participants[]: passer/receiver/passDefender with real athlete IDs.
//
// ESTIMATED, NOT DIRECTLY READ:
//   - "Medium" depth tier does not exist in ESPN's text (only
//     short/deep are ever tagged). Medium is approximated by splitting
//     ESPN's "short" tag using statYardage >= 7 as a threshold — this
//     is a judgment call, not a precise air-yards reading, because true
//     air yards (ball distance in flight) isn't exposed here; gained
//     yardage includes YAC. Flagged in the UI, not presented as exact.
//
// CONFIRMED ABSENT — will not be built:
//   - Coverage type (man/zone) or defensive personnel shape. Not in
//     this schema. PFF/NGS-tier data, not available via ESPN's public
//     API anywhere confirmed in this project.

const CORE = 'https://sports.core.api.espn.com/v2/sports/football/leagues/nfl'

export type PlayDepth = 'short' | 'medium' | 'deep' | null
export type PlayDirection = 'left' | 'middle' | 'right' | null

export type ParsedPlay = {
  id: string
  text: string
  typeText: string
  teamId: string | null
  isPass: boolean
  isRush: boolean
  isShotgun: boolean
  isComplete: boolean | null   // null for non-pass plays
  depth: PlayDepth
  direction: PlayDirection
  statYardage: number
  isRedZone: boolean           // start.yardsToEndzone <= 20
  down: number
  distance: number
  passerAthleteId: string | null
  receiverAthleteId: string | null
passerAthleteRef: string | null
  receiverAthleteRef: string | null
}


// Extracts depth from ESPN's own text. "deep" is authoritative; "short"
// gets subdivided into short/medium using yardage (see file header).
function classifyDepth(text: string, statYardage: number): PlayDepth {
  const lower = text.toLowerCase()
  if (lower.includes('deep')) return 'deep'
  if (lower.includes('short')) return statYardage >= 7 ? 'medium' : 'short'
  return null
}

function classifyDirection(text: string): PlayDirection {
  const lower = text.toLowerCase()
  // Order matters: check "middle" before generic left/right substrings
  // could false-match inside a player's name or team abbreviation.
  if (/\bmiddle\b/.test(lower)) return 'middle'
  if (/\bleft\b/.test(lower)) return 'left'
  if (/\bright\b/.test(lower)) return 'right'
  return null
}

async function resolveRef<T = any>(ref: string | undefined): Promise<T | null> {
  if (!ref) return null
  try {
    const res = await fetch(ref, { next: { revalidate: 3600 } })
    if (!res.ok) return null
    return await res.json()
  } catch {
    return null
  }
}

export async function getGamePlays(eventId: string): Promise<ParsedPlay[]> {
  try {
    const res = await fetch(
      `${CORE}/events/${eventId}/competitions/${eventId}/plays?limit=300`,
      { next: { revalidate: 3600 } }
    )
    if (!res.ok) return []
    const data = await res.json()
    const items: any[] = data.items ?? []

    const parsed: ParsedPlay[] = items.map(p => {
      const typeText: string = p.type?.text ?? ''
      const text: string = p.text ?? ''
  const isPass = typeText === 'Pass Incompletion' || typeText === 'Pass Reception'
const isRush = /rush/i.test(typeText)
const isComplete = isPass ? typeText === 'Pass Reception' : null
      const statYardage = Number(p.statYardage ?? 0)

      const passer = (p.participants ?? []).find((pt: any) => pt.type === 'passer')
      const receiver = (p.participants ?? []).find((pt: any) => pt.type === 'receiver')

      // Extract athlete id from the $ref URL (.../athletes/{id}?...)
      function idFromRef(ref: string | undefined): string | null {
        if (!ref) return null
        const m = ref.match(/athletes\/(\d+)/)
        return m ? m[1] : null
      }

      return {
        id: p.id,
        text,
        typeText,
        teamId: p.team?.$ref?.match(/teams\/(\d+)/)?.[1] ?? null,
        isPass,
        isRush,
        isShotgun: /\(shotgun/i.test(text) || /\(no huddle,\s*shotgun/i.test(text),
        isComplete,
        depth: isPass ? classifyDepth(text, statYardage) : null,
        direction: (isPass || isRush) ? classifyDirection(text) : null,
        statYardage,
        isRedZone: (p.start?.yardsToEndzone ?? 100) <= 20,
        down: p.start?.down ?? 0,
        distance: p.start?.distance ?? 0,
        passerAthleteId: idFromRef(passer?.athlete?.$ref),
        receiverAthleteId: idFromRef(receiver?.athlete?.$ref),
        passerAthleteRef: passer?.athlete?.$ref ?? null,
receiverAthleteRef: receiver?.athlete?.$ref ?? null,
      }
    })

    return parsed
  } catch (e) {
    console.error(`getGamePlays(${eventId}) error:`, e)
    return []
  }
}

// ── Aggregations for QB Room ────────────────────────────────────────────

export type QBRoomSummary = {
  passerAthleteId: string
  totalAttempts: number
  completions: number
  shotgunAttempts: number
  underCenterAttempts: number
  redZoneAttempts: number
  redZoneCompletions: number
  zoneChart: Record<string, { attempts: number; completions: number }>  // key: "depth-direction"
}

export function summarizeQBRoom(plays: ParsedPlay[], passerAthleteId: string): QBRoomSummary {
  const passPlays = plays.filter(p => p.isPass && p.passerAthleteId === passerAthleteId)

  const zoneChart: Record<string, { attempts: number; completions: number }> = {}
  for (const depth of ['short', 'medium', 'deep']) {
    for (const dir of ['left', 'middle', 'right']) {
      zoneChart[`${depth}-${dir}`] = { attempts: 0, completions: 0 }
    }
  }

  let shotgunAttempts = 0
  let underCenterAttempts = 0
  let redZoneAttempts = 0
  let redZoneCompletions = 0
  let completions = 0

  for (const play of passPlays) {
    if (play.isShotgun) shotgunAttempts++
    else underCenterAttempts++

    if (play.isRedZone) {
      redZoneAttempts++
      if (play.isComplete) redZoneCompletions++
    }

    if (play.isComplete) completions++

    if (play.depth && play.direction) {
      const key = `${play.depth}-${play.direction}`
      if (zoneChart[key]) {
        zoneChart[key].attempts++
        if (play.isComplete) zoneChart[key].completions++
      }
    }
  }

  return {
    passerAthleteId,
    totalAttempts: passPlays.length,
    completions,
    shotgunAttempts,
    underCenterAttempts,
    redZoneAttempts,
    redZoneCompletions,
    zoneChart,
  }
}

// Target share across all receivers for a game — feeds the "Targets" part of QB Room.
export function summarizeTargets(plays: ParsedPlay[]): Array<{ athleteId: string; targets: number; receptions: number }> {
  const byReceiver = new Map<string, { targets: number; receptions: number }>()

  for (const play of plays) {
    if (!play.isPass || !play.receiverAthleteId) continue
    const entry = byReceiver.get(play.receiverAthleteId) ?? { targets: 0, receptions: 0 }
    entry.targets++
    if (play.isComplete) entry.receptions++
    byReceiver.set(play.receiverAthleteId, entry)
  }

  return Array.from(byReceiver.entries())
    .map(([athleteId, v]) => ({ athleteId, ...v }))
    .sort((a, b) => b.targets - a.targets)
}